### ISSUE TITLE
VSIX package for VS12 (2013) is not built (?)

### ISSUE THREAD

**Issue by cw2** [NETMF/netmf-interpreter#127]
VSIX package for VS 2013 is not built (warning NETMF: Visual Studio 2013 SDK not found VSIX package will not be generated), because `VSSDK12INSTALLDIR` variable is empty - its initialization was removed from `setenv_sdk` in commit 4643ab8a1129006546235eecdf803d7ac62fde5a. Is this intentional?

**Comment by smaillet-ms** [comment]
Not intentional but fixed in a subsequent commit

**Comment by cw2** [comment]
Sorry, but it was broken again in subsequent commit - you can see in the current version the lines are missing.

**Comment by smaillet-ms** [comment]
Fixed in #130
