### ISSUE TITLE
Eliminate or suppress warnings for build_sdk (VS14)

### ISSUE THREAD

**Issue by cw2** [NETMF/netmf-interpreter#128]
After upgrade to VS14 (2015) the build process started from build_sdk.cmd generates a number of warnings:

#### C++ Compiler warnings
warning C4267: '=': conversion from 'size_t' to 'short', possible loss of data
warning C4838: conversion from '\<type1>' to '\<type2>' requires a narrowing conversion

#### Code Analysis warnings
In Debug configuration there are 500+ Code Analysis warnings.

**Comment by cw2** [comment]
I volunteer to fix (in NETMF code) and suppress (in 3rd party libs, OpenSSL) C++ compiler warnings.

I am not sure what to do with Code Analysis warnings.

**Comment by smaillet-ms** [comment]
Yes, the VS2015 compiler is more aggressive and picky about things and the OpenSSL code is particularly covered in legal but potentially problematic code. It's very difficult to write portable C or C++ code that doesn't trigger warnings on at least one compiler somewhere.

**Comment by smaillet-ms** [comment]
Fixed with pull request #132
