### ISSUE TITLE
Build errors due to missing SolutionWizard projects

### ISSUE THREAD

**Issue by cw2** [NETMF/netmf-interpreter#141]
The build_sdk (in `dev` branch) reports two missing solution wizard-related projects: `WizardSupport.csproj` and `SolutionWizard.csproj`, which were removed, but are still referenced from `CLR\Tools\PlatformDesigner\build.dirproj` that is included from the root `build.proj`, because the condition is true:
```
<Project 
        Condition="EXISTS('$(SPOCLIENT)\CLR\Tools\PlatformDesigner\build.dirproj')"
        Include="
        Product\build.dirproj;
        CLR\Tools\PlatformDesigner\build.dirproj;
        tools\scripts\port\Sample\build.dirproj"
        />
```
I guess the reference(s) should be removed from one of the other build.dirproj.

**Comment by mortezag** [comment]
You are right. Thanks. Just sent the pull-request #142
