### ISSUE TITLE
Support-GCC: Broken USB enumeration due to invalid wchar_t size

### ISSUE THREAD

**Issue by cw2** [NETMF/netmf-interpreter#193]
The removal of `-fshort-wchar` compiler option in `Microsoft.Spot.system.gcc.targets` (commit 2ddde0a50dad496b9eb5627bd4b8da11d5903eaf) causes USB configuration structure to be compiled with 4-byte `wchar_t`, which results in broken USB enumeration.

I guess the option was removed to get rid of _"... uses 2-byte wchar_t yet the output is to use 4-byte wchar_t"_ linker warning.

To fix the problem, either `-fshort-wchar` has to be brought back (along with `--no-wchar-size-warning` LINK_FLAG to suppress the warning), or `USB_STRING_CHAR` type (and maybe others) has to be changed to something else than `wchar_t`.

I have a pull request ready for the former case...

**Comment by smaillet-ms** [comment]
Nice catch... I wrestled with the right solution to that wchar_t mismatch warning as it is indicative of real problems. However, assuming it is only from the C runtime libs and furthermore that the only parst of those libs that care we don't ultimately use then suppressing the warning is viable.
