### ISSUE TITLE
Help appreciated on build issue

### ISSUE THREAD

**Issue by robvanschelven** [NETMF/netmf-interpreter#209]
I get build errors on both STM32F4Discovery as well as on MCBSTM32F400
Build_SDK and windows2 build proceed without errors

Anyone a suggestion? Thanks in advance!

![stm32buildoutput](https://cloud.githubusercontent.com/assets/8533077/8343412/519386cc-1ad5-11e5-829f-1f3dc1d2a40b.png)

**Comment by smaillet-ms** [comment]
I'm not clear on the message as I'm not fluent in that particular language :grin: However I can see from the command window title you have used setenv_vs - which won't work for a solution build targeting the STM32F400. You need to use a new command prompt window using setenv_gcc or setenv_mdk depending on the tool set you are using. mixing setenv_xxx calls in the same command window is not generally a supported scenario.

**Comment by robvanschelven** [comment]
PLATFORM_INDEPENDENT_LIB_DIR wasn't defined because of a failure i made typing the compiler version :( Now i was able to build MCBSTM32F400 however STM32F4DISCOVERY builds with 1 error

![stm32mf-fail](https://cloud.githubusercontent.com/assets/8533077/8355321/ea4d2dc2-1b4e-11e5-90ad-bae3b669bd91.png)

**Comment by cw2** [comment]
Please update to the latest version, that (#204) was fixed in pull request #205.

**Comment by robvanschelven** [comment]
Thanks @cw2 that solved the problem!
