### ISSUE TITLE
Regex match "out of range exception"

### ISSUE THREAD

**Issue by ppatierno** [NETMF/netmf-interpreter#220]
Hi,

I think I found a bug on Regex matching. I wrote a blog post on it few weeks ago. Following the link to avoid to re-write it. I hope it's well.

http://www.embedded101.com/Blogs/PaoloPatierno/entryid/617/net-micro-framework-and-regular-expressions-out-of-range-exception

Thanks,
Paolo.

**Comment by mortezag** [comment]
@ppatierno I tried your regex pattern on strings with very long groups but I could not repro this issue. (for example, "key1=value1;key2=vaaaaaaa...aaaaaaalue2;key3=value3", where ... represents over 200 'a'). Please let me know your input string or a sample which causes the exception.

I close the bug as no-repro for now. Please reopen it with your sample.
