### ISSUE TITLE
Dev branch: TOTAL_USART_PORTS wrong?

### ISSUE THREAD

**Issue by maiorfi** [NETMF/netmf-interpreter#246]
It seems that setting TOTAL_USART_PORTS=1+6 (i.e. including ITM0) breaks STM32F4_USART_Functions.cpp, where TOTAL_USART_PORT seems not taking into account ITM0 extra port. Indeed, STM32F4Discovery solution building fails because of missing definitions for USART7 and USART8.

**Comment by cw2** [comment]
This is fixed in pull request #245.
