### ISSUE TITLE
Is SDK 4.4 in VS 2015 suitable in order to build and debug projects based on 4.3.1 target framework?

### ISSUE THREAD

**Issue by maiorfi** [NETMF/netmf-interpreter#292]
Hi.

I just spotted an issue that could be related to VS2015 toolchain use with .NETMF 4.3.1 SDK.

Specifically I get a MMP error, kind of "cannot process method declaration" while building a 3rd party class library (despite such method declaration doesn't actually seem so special).

So my question is: is there any way I can use VS2015 with NETMF 4.3.1 target framework? It seems that SDK4.4 enables only use of 4.4 target framework. Maybe both sdk can live side by side?

Thanks!

**Comment by smaillet-ms** [comment]
In v4.4 SDK the only libraries included are for V4.4. If you want to target an earlier SDK then you need to install that. In previous releases all the old binaries were rolled into a single big installer that mad the installer bigger and the creation of the installer significantly more complex. The major reason for this bundling was that the SDK had to be updated for each version of VS supported and we didn't want to force updates just to use a new version of VS. Now that the SDK and VS integration are separated there is no longer a need to keep it all bundled thus reducing build complexity and eliminated a large binary burden on the version control system, which otherwise had to keep all the released binaries checked in.

**Comment by maiorfi** [comment]
Thanks.

So, to summarize, in my scenario I can install 4.3.1 SDK (with whatever target framework among 4.1, 4.2 and 4.3) and install VS2015 VSIX package. Right?

Also, could I install both 4.3.1 and 4.4 sdks side-by-side and use them with VS2015 VSIX in order to work both on old and new projects?

**Comment by smaillet-ms** [comment]
Yes, the VSIX packages were designed to work with any installed SDKs (Just like the desktop version supports targeting multiple versions). Thus all future SDKs will come with only the binaries for a single version of NETMF.

**Comment by maiorfi** [comment]
Mmmm...just tried compiling a 4.3 targeted project both with VS2015 and VS2013  with both SDK 4.3.2 RTM and 4.4 and I get:

MMP : error MMP0000: 0x80131700

...tried to uninstall sdk 4.4 and vsix14...but issue still arises...

...any suggestion (for sake of completeness, my system has been recently updated to Windows 10)?

**Comment by maiorfi** [comment]
...never mind...it was due to this:

http://stackoverflow.com/questions/4321114/0x80131700-build-error-on-net-micro-framework

**Comment by maiorfi** [comment]
...sorry for all this noise, but finally I succeeded in reproducing the original issue, this is the error I get when I build a project (specifically the modbus library shared on GHI codeshare by Reinhard Ostermeier):

error MMP0000: Cannot parse method signature 'ReadDeviceIdentification'
1>MMP : error MMP0000: CLR_E_FAIL

where ReadDeviceIdentification method signatures (more than one overload):

```C#
public virtual DeviceIdentification[] ReadDeviceIdentification(byte deviceAddress, ModbusConformityLevel deviceIdCode, int timeout = 2000)

public virtual DeviceIdentification[] ReadDeviceIdentification(byte deviceAddress, ModbusConformityLevel deviceIdCode, ref ModbusObjectId objectId, out bool moreFollows, int timeout = 2000)

public virtual DeviceIdentification ReadSpecificDeviceIdentification(byte deviceAddress, ModbusObjectId objectId, int timeout = 4000)
```

Any idea?

**Comment by smaillet-ms** [comment]
Hmmm not a clue, nothing in the signatures looks funky and we aren't using the Roslyn compiler so it's not like a change in the compiler did something.

**Comment by maiorfi** [comment]
Any news about that? Thanks!

**Comment by martincalsyn** [comment]
If you are compiling 4.3.1 under VS2015, try the patch from here: https://www.ghielectronics.com/community/codeshare/entry/1053

For 4.4, the msbuild files force use of the older compiler, but the 4.3.* msbuild files did not have that restriction and defaulted to the Roslyn compiler, which results in generating IL that is not compatible with the netmf interpreter. I think the problem you describe may be related.

**Comment by maiorfi** [comment]
Great contribution!

Thanks Martin: works like a charm :smile:
