### ISSUE TITLE
MetaDataProcessor stack corruption due to COR_ILMETHOD_DECODER incompatibility

### ISSUE THREAD

**Issue by elasota** [NETMF/netmf-interpreter#293]
MetaData::Parser::ParseByteCode and MetaData::Parser::Dump_EnumTypeDefs create COR_ILMETHOD_DECODER instances on the stack, and the constructor in turn calls DecoderInit, which is statically linked in from format.lib.

DecoderInit fully initializes the COR_ILMETHOD_DECODER instance, but a "cbLocalVarSig" field was added to it at some point that isn't present in the corhlpr.h in the NETMF Tools dir.
See: https://github.com/dotnet/coreclr/blob/master/src/inc/corhlpr.h

Because of this, stack corruption occurs when MetaDataProcessor is compiled against newer Windows kits and -parse is used.

**Comment by smaillet-ms** [comment]
Can you provide a step by step sequence to reproduce the problem?

**Comment by elasota** [comment]
Nevermind, turns out it was a bad build that wasn't linking the CorHelper project correctly.
