### ISSUE TITLE
missing vsix

### ISSUE THREAD

**Issue by fredrik-ngenic** [NETMF/netmf-interpreter#30]
Hi,
don't know if this is the right place but...

When i run the build_sdk.cmd I get the sdk msi in the place that is mentioned in the wiki,
but the vsix files aren't where they're supposed to (BuildOutput\public\Release\Server\dll).
And I can't find them anywhere else either...
Any ideas?

Regards 
Fred

**Comment by smaillet-ms** [comment]
This is the perfect place to ask such questions!
Sounds like you don't have the Visual Studio SDK installed. The build system will skip generating the VSIX files if it detects the SDK is not installed. Now that we've cleaned up the SDK build it's probably worth generating an informative message on that. (e.g. if the build is skipping a particular VSIX it should print a message to ley you know it is doing so and why)

**Comment by mortezag** [comment]
Maybe related to #33

**Comment by fredrik-ngenic** [comment]
Thank you,
I'll look into that
