### ISSUE TITLE
10048 error on starting HttpListner on a recently closed port

### ISSUE THREAD

**Issue by mortezag** [NETMF/netmf-interpreter#314]
In HttpTests, there is a HttpServer class which opens a HttpListner on a specific port. Many of the tests create a HttpServer, do some actions, and close the HttpServer at the end. If the next test tries to create another HttpServer but on the same port, error 10048 occurs. This may be due to the fact that Linger/DontLinger options are not supported in the new stack anymore.

**Comment by lt72** [comment]
This is caused by the lack of Linger support lwIP stack. Please update the tests to track and reflect the new behavior.
