### ISSUE TITLE
fix for emulator so it doesn't block when there is no data on a SSL connection

### ISSUE THREAD

**Issue by josesimoes** [NETMF/netmf-interpreter#330]
This is fix that as been proposed by Xin Chen of the AMQP Lite project.
See:
http://amqpnetlite.codeplex.com/wikipage?title=NETMF%20and%20TLS%2fSSL%20connection&referringTitle=Documentation

**Comment by smaillet-ms** [comment]
Please submit the change as a pull request so it can be reviewed and merged into the main code repository.

**Comment by josesimoes** [comment]
Done! PR #342
