### ISSUE TITLE
NOT AN ISSUE - congratulations on v4.4

### ISSUE THREAD

**Issue by josesimoes** [NETMF/netmf-interpreter#332]
:tada:  :tada: :tada:

Lacking a better place for this allow me to open an issue for praising the Microsoft team that worked on this release and of course all the community members that contributed with bug reports, suggestions and code. I would say that it was a good team effort.

After popping the champagne lets get back to work with the next release. There is a lot of work ahead! :smile:  

PS: .NETMF should have a dedicated forum... doesn't it deserve an MSDN forum like any other Microsoft product/technology!?

**Comment by Elastino** [comment]
Congratulations! everyone!
