### ISSUE TITLE
Build troubles with CODESIGN.Submitter

### ISSUE THREAD

**Issue by maiorfi** [NETMF/netmf-interpreter#333]
Hi.

I can't build any firmware solution neither sdk since I get always following errors I can't spot what could depend on.

I uploaded full log at https://dl.dropboxusercontent.com/u/7414592/TinyCLR.it/msbuild_log.zip but it seems that root problem is (please forgive italian msbuild log):

error CS0246: Il nome di tipo o di spazio dei nomi 'CODESIGN' non è stato trovato. Probabilmente manca una direttiva using o un riferimento all'assembly. [D:\NETMF\netmf-interpreter\Framework\Tools\BuildTasksInternal\BuildSigner\BuildSignerSpotBuild.csproj]

i.e. cannot find "CODESIGN.Submitter" assembly...

...any hint?

Thanks!

**Comment by maiorfi** [comment]
Ok, it seems that netmf-interpreter\Framework\Tools\BuildTasksInternal\BuildSigner\BuildSignerSpotBuild.csproj contains a bad hint for CODESIGN.Submitter.dll, so changing:

$(MSBuildProgramFiles32)\Microsoft Internal\Codesign.Submitter\CODESIGN.Submitter.dll

with

$(SPOROOT)\tools\x86\CODESIGN\CODESIGN.Submitter.dll

makes msbuild happy again :smile:

**Comment by smaillet-ms** [comment]
Thanks for the info. We really need to disable or remove that stuff from the non-internal build as it's not something that could ever work outside of our internal infrastructure.
