### ISSUE TITLE
pending PRs

### ISSUE THREAD

**Issue by josesimoes** [NETMF/netmf-interpreter#344]
Hey,

Any chance the pending PRs are reviewed and officially merged (specially the oldest ones)?

Thanks!

**Comment by smaillet-ms** [comment]
Done - mostly
#343 needs to be squashed first (Lot's of merge commits can be removed in a squash)
#341 is more of a workaround than a real fix and as the comments point out introduces potential new issues with using PLATFORM_EMULATED_FLOATINGPOINT
#273 is an open discussion, based on the comments isn't work that is complete (We don't have DS-5 lic. internally so we can't test or verify that works, nor can we really maintain it, so anyone wanting to add another toolchain will need to step up and be willing to commit to test and maintenance for the longer term so it doesn't go stale)

**Comment by josesimoes** [comment]
:+1:
