### ISSUE TITLE
Where should I put __FPU_PRESENT

### ISSUE THREAD

**Issue by techcap** [NETMF/netmf-interpreter#345]
When I build the project, it said "#warning "Compiler generates FPU instructions for a device without an FPU (check __FPU_PRESENT)" at core_cm4.h

__FPU_PRESENT is defined in stm32f4xx.h.
But I cannot find how to remove above warning.

Temporarily I put "TinyCLR_Defines Include="__FPU_PRESENT" in /CMSIS/CMSIS/RTOS/RTX/dotNetMF.proj.

Can you suggest better solution?

**Comment by smaillet-ms** [comment]
Don't set it anywhere, ignore the warning - it's due to the way the CMSIS headers are setup and used by the RTX libs - it's harmless.

**Comment by techcap** [comment]
Thanks.^^
