### ISSUE TITLE
Discovery4 solution authoring attempt

### ISSUE THREAD

**Issue by maiorfi** [NETMF/netmf-interpreter#35]
Hi.

I'm trying to author a solution for Discovery4 and, even though I succeeded in running TinyBooter, I have TinyClr "throwing" a BusFault error very early in bootstrapping code.

More in details, SystemInit() runs without hiccups, but soonafter, when AppEntry.s jumps to __main() function, located into tinyclr_dat.s, troubles happen, with situation depicted in following screenshot:

https://dl.dropboxusercontent.com/u/7414592/Embedded/NETMF44_Binaries/BusFault_Screenshot.png

I'm not an expert, but it seems that such issue could be related to a "bad" scatterfile, that I uploaded for reference here: https://dl.dropboxusercontent.com/u/7414592/Embedded/NETMF44_Binaries/TinyCLR_Scatterfile.7z

Also, I was wondering whether commenting out all things related to Network support could have removed too much of CMSIS_RTX stuff, so I uploaded also my TinyCLR.proj here: https://dl.dropboxusercontent.com/u/7414592/Embedded/NETMF44_Binaries/TinyCLR.proj

Thank you very much!

**Comment by smaillet-ms** [comment]
A bus fault in early boot is usually the result of scatter file placing zero init or initialized writeable dat into an invalid address. It can also occur if the interrupt vector table is placed in an improperly aligned address. Check your device manual for vector table alignment requirements and double check the generated map file for where the tools ended up placing your sections listed in the scatterfile XML.
