### ISSUE TITLE
MFDeploy 4.4 does not show Discovery4 with tinybooter, while 4.3 does.

### ISSUE THREAD

**Issue by ktos** [NETMF/netmf-interpreter#357]
I tried to compile NETMF 4.4 for my STM32Discovery with GCC ARM 4.8.3. I built a tinybooter and wrote it onto chip using ST-LINK. It started, is showing all 4 LEDs glowing. Now, when connected, MFDeploy from 4.4 SDK does not show my device under USB, while MFDeploy from 4.3 does.

Device is recognized as "STM32 .Net Device" in device manager in tinybooter, with USB\VID_0483&PID_A08F (WinUSB Device).

By the way, I tried also to build whole CLR, but after deploying ER_CONFIG and ER_FLASH onto Discovery4 it does not boot up (USB device not recognized).

**Comment by maiorfi** [comment]
Please take a look to issue #348
