### ISSUE TITLE
Build Date wrong for 2016

### ISSUE THREAD

**Issue by SytechDesigns** [NETMF/netmf-interpreter#367]
Last month ( Dec 2015), every port I built, when tested with MFDeploy (Device Capabilities) reported a software version build date that was correct.
However every thing I have built since Jan 1 2016 reports a build date of Dec 31 2015 - irrespective of the build date. Any one have any ideas on this?

**Comment by SytechDesigns** [comment]
How does the project constant **DATE** get set in the build process?

**Comment by SytechDesigns** [comment]
That should be __ DATE__

**Comment by smaillet-ms** [comment]
**DATE** is a compiler generated pre-processor macro that is set to the date of the compilation. Thus, if you have libraries built on different days without doing a clean build of them all they will all have different values for **DATE**. Try doing a clean build, and you should see the current date correctly.
