### ISSUE TITLE
PAL interfaces to OS & HAL

### ISSUE THREAD

**Issue by Bsvt** [NETMF/netmf-interpreter#372]
How to get the list of interfaces from PAL to OS & PAL to HAL?
(Which file should I look into to get above list?)

**Comment by smaillet-ms** [comment]
There's no single list anywhere at this point unfortunately. That's an area of documentation I've wanted to find the time to tackle for a while now. There are a number of header files in %SPOCLIENT%\DeviceCode\Include that define the majority of the HAL and PAL.

**Comment by Bsvt** [comment]
Got it. Thanks.
