### ISSUE TITLE
where is CLR_Defines.h?

### ISSUE THREAD

**Issue by kmshim** [NETMF/netmf-interpreter#378]
hi, @smaillet-ms 
Cloned information

> SHA-1: eb4596e9a599c8b62498bca22b78caa825202e0e
> - Merge pull request #354 from DerekGn/dev
>   Removed assembly signing key

I know that this header file,CLR_Defines.h, had been in the \CLR\Include.
but now this file is not exist in that path.
is this header file missing? or moved to the other path?

**Comment by miloush** [comment]
Looks like it needs to be built?

https://github.com/NETMF/netmf-interpreter/blob/34a92c3d79d3d1c48440dc32f88d5b81095311a4/Framework/Tools/CreateCLRDefines.proj

**Comment by lt72** [comment]
the header is automatically generated during the build by this msbuild task:

GenerateCLRDefines 

it is generated into the platform independent portion of the build directory.

**Comment by kmshim** [comment]
Thanks for your help.
