### ISSUE TITLE
Use MIT License instead of Apache License

### ISSUE THREAD

**Issue by markusjohnsson** [NETMF/netmf-interpreter#38]
Now that CoreCLR and CoreFX has been released under the MIT license, wouldn't it make sense to change the license of .NET Micro Framework to MIT license too?

**Comment by smaillet-ms** [comment]
Thanks for the feedback. We're considering that for the next major release. It's doubtful we'd do so for the current release as we have contributions from multiple sources and just changing the lic. from what they submitted isn't a very nice thing to do (let alone legal!). While it's probably possible to resolve that - it would likely entail a bunch of work involving a lot of time with lawyers. You can probably guess how much fun that can be!
