### ISSUE TITLE
How to modify arm tool chain settings in NETMF?

### ISSUE THREAD

**Issue by Bsvt** [NETMF/netmf-interpreter#380]
Is arm build for STM32f4 supported for both eabi & none-eabi ?
Currently, I see arm-none-eabi is set in setenv_base; if I modify it to use arm-eabi, will it work?

**Comment by smaillet-ms** [comment]
Well I can think of one sure way to find out - try it! :grin: 
I can't think of a reason it wouldn't work, what do you expect to be different?

**Comment by Bsvt** [comment]
Tried & it worked. No problem.:)
