### ISSUE TITLE
xml syntax error of Tools_Include.vcproj in the CLR\Tools\Include.

### ISSUE THREAD

**Issue by kmshim** [NETMF/netmf-interpreter#381]
hi, @smaillet-ms 
I found the syntax error of Tools_Include.vcproj .
 line number: 317

**Comment by smaillet-ms** [comment]
VCProj files aren't used anymore - those are for VS 2008 and earlier. We just haven't deleted them all yet.

**Comment by kmshim** [comment]
Thanks for your information.
