### ISSUE TITLE
Tweaks in gcc.targets for GCC 5-2015-q4-major

### ISSUE THREAD

**Issue by josesimoes** [NETMF/netmf-interpreter#397]
I've been doing some tweaking in the gcc.target with the lattest GCC version.
Mostly optimizations and adding extra debug information to debug images.
Should I open a new PR for this?

**Comment by smaillet-ms** [comment]
Can you be more specific on the tweaks? What happens if someone doesn't have that particular release? (e.g. will it just work?, gracefully fall back? or crash? )

**Comment by josesimoes** [comment]
Mostly flags asked to optimize the outputs for "bare metal" systems that I've been collecting when going through the documentation and reading forums.
Considering that newlib nano is already separated and optional all the others are pretty straightforward, I would say. They are not exclusive of this version although the compiler flags can produce different results. In the end I don't think there'll be any catastrophic result.

**Comment by smaillet-ms** [comment]
OK, sounds like something worthy of a PR without further discussion then.
