### ISSUE TITLE
Adding support for non Cortex CPUs

### ISSUE THREAD

**Issue by doingnz** [NETMF/netmf-interpreter#441]
I would like to have NetMF 4.4 running on our older Arm920T based HW as we are not in a position to change to Cortext CPU at the moment. 

I assume the future of NetMF will include processors other than Cortex?

Basic approach is to clone the current DeviceCode\Cores\arm\Processors\CortextMx to a new folder DeviceCode\Cores\arm\Processors\ARM9. Then rework the files from Cortex to ARM9, keeping existing file names and structure as in Cortext as much as possible.

Anything else I should know ?

**Comment by smaillet-ms** [comment]
You might find it easier to port over the ARM9 code from the older codeplex source tree. Given the number of non-Cortext CPUs going on to the "not to be used in new diesgns" bucket we didn't bring any of those forward into github and v4.4. NETMF itself is CPU and platform agnostic, as long as you have a 32 bit processor and a reasonably modern C++ compiler you should be able to get a port done.
