### ISSUE TITLE
vectorial / XAML logo

### ISSUE THREAD

**Issue by aline-almeida** [NETMF/netmf-interpreter#445]
Hi!

Is there a vectorial (XAML, if possible) logo of MicroFramework?
https://msopentech.com/wp-content/uploads/NetMF-2-300x283.png

Thanks,
Aline

**Comment by smaillet-ms** [comment]
There might have been one - I'll need to lookup who created that originally (it's a variant of the one from .NET foundation). Might I inquire as to what you wish to use it for?

**Comment by aline-almeida** [comment]
Hi!
Thanks, it would be nice to have that.
It's for an app I'm developing.

**Comment by aline-almeida** [comment]
Just send pr #449 with this in case anyone else is interested.
Thanks anyway.
