### ISSUE TITLE
Why different definitions for <BUILD_TEST_ROOT> and related values?

### ISSUE THREAD

**Issue by doingnz** [NETMF/netmf-interpreter#453]
in 'tools\Targets\Microsoft.SPOT.Build.Setup.Targets'

```
    <BUILD_TREE>$(BUILD_ROOT)\$(Configuration)</BUILD_TREE>
    <BUILD_TEST_ROOT>$(BUILD_TREE)\Test</BUILD_TEST_ROOT>
    <BUILD_TEST_TREE>$(BUILD_TREE)\Test</BUILD_TEST_TREE>
    <BUILD_TEST_TREE_CLIENT>$(BUILD_TEST_TREE)\Client</BUILD_TEST_TREE_CLIENT>
    <BUILD_TEST_TREE_SERVER>$(BUILD_TEST_TREE)\Server</BUILD_TEST_TREE_SERVER>
```

in 'tools\Targets\Microsoft.SPOT.Test.CSharp.Targets'

```
    <BUILD_TEST_ROOT>$(BUILD_ROOT)</BUILD_TEST_ROOT>
    <BUILD_TEST_TREE>$(BUILD_TEST_ROOT)\$(Configuration)\Test</BUILD_TEST_TREE>
    <BUILD_TEST_TREE_PLATFORM>$(BUILD_TEST_TREE)\$(TinyCLR_Platform)</BUILD_TEST_TREE_PLATFORM>
    <BUILD_TEST_TREE_DLL>$(BUILD_TEST_TREE_PLATFORM)\dll</BUILD_TEST_TREE_DLL>
```

Any thoughts why BUILD_TEST_TREE_CLIENT and BUILD_TEST_TREE_SERVER are not defined in Microsoft.SPOT.Test.CSharp.Targets?

**Comment by smaillet-ms** [comment]
the various XXX_CLIENT and XXX_SERVER definitions are intended for generally only in the context of building the SDK (and the artist formerly known as the Porting kit). I'd guess the intent is that the test targets was something intended for use by the test "sdk". Unless something is horribly broken by it I'm not going to lose any sleep on this as the goal going forward is to completely replace the mess we call the NETMF build system.
