### ISSUE TITLE
mf4.3 qfe1/qfe2

### ISSUE THREAD

**Issue by SytechDesigns** [NETMF/netmf-interpreter#470]
I was under the impression that there was no difference in the mfport for qfe1 and qfe2. that the only difference was in the sdk. However I have a suspicion that there are some differences - but if you go to the old codeplex site there is no download for the mfport code for qfe2, just the sdk and vsix files - so your only option is to try and download from the 'source' window - but there is something wrong with this codeplex page - it is very slow to switch into the source page and when you try and download the page always times out - so I am unable to download the source so I can do a complete diff between qfe1 and qfe2. However looking at the history - it looks like the only changes were to the sdk.
Can any one ( Steve?) clarify what is different between qfe1 and qfe2 and also how can I download a copy of the qfe2 source - and yes I know we are supposed to be using 4,4 ( and I am) - but we do have legacy projects to maintain.
thanks

**Comment by smaillet-ms** [comment]
QFE2 made no changes to the NETMF itself. It only changed the SDK to support modern tools. There was no porting kit for QFE2 - only the SDK was updated so there couldn't have been any other changes.
