### ISSUE TITLE
File System - High capacity Micro SD Cards

### ISSUE THREAD

**Issue by rrideAMT** [NETMF/netmf-interpreter#543]
To this point I have been successfully using a 2GB Micro SD Card, standard capacity with my NETMF port.

I am testing a 4GB and 8GB Micro SD Card high capacity card, and these cards cause System.IO.IOExceptions to be thrown when my managed application attempts to SetCurrentDirectory and list any sub directories.  The System.IO.IOExceptions are created by a CLR_E_DIRECTORY_NOT_FOUND and CLR_E_INVALID_DRIVER exceptions.

Is the NETMF File System able to support the high capacity cards up to 32GB for FAT32 format?

Do I need to format the high capacity SD card differently?

It looks like there is some limitation in the File System implementation.  I found that the call to 
BOOL FAT_LogicDisk::MountDisk() from 
BOOL FAT_LogicDisk::IsLoadableMedia( BlockStorageDevice* driverInterface, UINT32* numVolumes ) returns FALSE
during the Mounting process.
This results in the pointer fsDriver in the FileSystemVolumeList::AddVolume() call to be null.
I am having difficulty in tracking down why the call to MountDisk() is failing.

Thanks for any help with this issue.

**Comment by doingnz** [comment]
The standard NetMF does not support SD Cards over 2 GB as the internal logic is using INT32 for sizes/offsets. These need to be 64 bit variables to work with SD Cards over 2 GB. 

I need to clean up my code and make a pull request ... the difficulty is a have a hard deadline for next week and can only look at this file IO update after that is done. I will need to catch up to where NetMF is currently to do the diff.
