### ISSUE TITLE
TristatePort .Active property causes unnecessary exception in managed code

### ISSUE THREAD

**Issue by Sukasa** [NETMF/netmf-interpreter#58]
This issue is to go along with the Pull Request #57 I submitted previously.

I've been bitten by this one a few times myself.  When managed code attempts to set the .Active property of a TristatePort object to the value it is currently set to, instead of simply doing nothing (as nothing needs to be done), the interpreter instead throws an InvalidOperationException.  This appears to be entirely an arbitrary design choice, as no code is avoided or skipped through the inclusion of the function that initiates the exception.  As well, it creates an increased workload for the user, as now they must work around this exception to duplicate the checks already present in unmanaged code.  This presents an increased learning curve that is not necessary, and serves only to make programming with Tristate ports more difficult.

The pull request i submitted removes the function call that causes the exception.  The effect of this upon managed code is that an exception is *not* thrown if the user attempts to write a value to the .Active property when the .Active property is already set to that value.  It does not prevent existing idioms such as `if(Port.Active <> NewValue) Port.Active = NewValue;`.

The idiom that would be affected is the use of try/catch to perform a different function if the code fails, for example:

    try {
      Port.Active = NewValue;
    } catch (InvalidOperationException ex) {
      // Do user logic here when NewValue == Port.Active
    }

**Comment by cw2** [comment]
Just for reference, this was also reported in CodePlex [issue 1871](http://netmf.codeplex.com/workitem/1871).
