### ISSUE TITLE
RunTests tool throws Win32Exception

### ISSUE THREAD

**Issue by mortezag** [NETMF/netmf-interpreter#78]
Trying to execute RunTests tool on any test solution using emulator, the tool returns Win32Exception. The exception is thrown from Microsoft.SPOT.Debugger library. Basically, BeginReadCore method in GenericAsyncStream class tries to read from the pipes/stream written to by emulator but in one call gets ERROR_BROKEN_PIPE. This broken pipe error apparently happens at the end of test run and close to when the debugger is going to close the stream. I noticed that the stream shows 1 character to read but when the debugger tries to read, the error happens.

Repro Steps:
1. run build_sdk.cmd in a command prompt
2. change directory to BuildOutput\public\Releases\Test\Server\dll
3. run RunTests.exe with -test [path to a test solution] -transport Emulator -device Microsoft

**Comment by smaillet-ms** [comment]
fixed by pull request #96
